#!/bin/bash
set -ex
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push arxivvanity/engrafo:latest
docker push arxivvanity/engrafo:${TRAVIS_COMMIT}
if [ -n "$TRAVIS_TAG" ]; then
    docker tag arxivvanity/engrafo:latest arxivvanity/engrafo:${TRAVIS_TAG}
    docker push arxivvanity/engrafo:${TRAVIS_TAG}
fi
