#!/bin/bash
ENGRAFO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

exec docker run \
    --init \
    -v "$(pwd)":/workdir -w /workdir \
    -v "$ENGRAFO_DIR:/app" \
    --rm \
    -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_S3_REGION_NAME \
    engrafo \
    engrafo "$@"
