#!/bin/bash
DIR=$(dirname "$1")
DIR="$(cd "$DIR" && pwd)" # make absolute
FILENAME=$(basename "$1")

ENGRAFO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

if [ ! -z "$PANDOC_BINARY" ]; then
  PANDOC_VOLUME_FLAG="-v $PANDOC_BINARY/$PANDOC_FILE:/usr/local/bin/pandoc"
fi

exec docker run \
    -v "$DIR":/workdir -w /workdir \
    -v "/app/node_modules" \
    -v "$ENGRAFO_DIR:/app" \
    --rm \
    $PANDOC_VOLUME_FLAG \
    engrafo /app/bin/render "$FILENAME"
