#!/bin/bash
DIR=$(dirname "$1")
DIR="$(cd "$DIR" && pwd)" # make absolute
FILENAME=$(basename "$1")

ENGRAFO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

exec docker run \
    -v "$DIR":/workdir -w /workdir \
    -v "/app/node_modules" \
    -v "$ENGRAFO_DIR:/app" \
    engrafo /app/bin/render "$FILENAME"
