#!/bin/bash
ENGRAFO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

exec docker run \
    --init \
    -v "$ENGRAFO_DIR:/app" \
    -w /app \
    -p 8000:8000 \
    -p 8001:8001 \
    --rm \
    -it \
    --entrypoint node \
    engrafo \
    bin/engrafo-server "$@"
