#!/bin/bash
ENGRAFO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

exec docker run \
    -v "$ENGRAFO_DIR:/app" \
    -w /app \
    -p 8010:8010 \
    -w /app/server/ \
    --rm \
    engrafo \
    python server.py
