#!/bin/bash
ENGRAFO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

exec docker run \
    -v "/app/node_modules" \
    -v "$ENGRAFO_DIR:/app" \
    --rm \
    -it \
    engrafo \
    node_modules/.bin/jest "$@"
