name: CI
on: [push]
jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"

      - name: Install Percy
        run: gem install percy-cli

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build
        run: |
          docker pull arxivvanity/engrafo:latest
          docker build -t arxivvanity/engrafo:latest -t arxivvanity/engrafo:${GITHUB_SHA} --cache-from arxivvanity/engrafo:latest .

      - name: Test
        run: docker run arxivvanity/engrafo yarn test-inside-docker

      - name: Percy
        run: script/ci-percy
        env:
          PERCY_TOKEN: b64c3ed80d514eeaafc7c61556db437e4ea36714919e7cce52176f4b7a14e2e9

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Push
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: |
          docker push arxivvanity/engrafo:latest
          docker push arxivvanity/engrafo:${GITHUB_SHA}

      - name: Push tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker tag arxivvanity/engrafo:latest arxivvanity/engrafo:${{ github.event.release.tag_name }}
          docker push arxivvanity/engrafo:${{ github.event.release.tag_name }}
